# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Whack_a_Jellyfish-Lon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Whack_a_Jellyfish-Lon
pod 'Each', '~> 1.2'
end
